### PR TITLE
Adds Connection Exception

### PR DESCRIPTION
**Pull request by StarDylan**

### CODE REVIEW

**Comment by starcode911** [comment]
I think this is not the right approach - you are basically making an additional HTTP call and even when that succeeds the actual phIn REST call can still fail - either the network just went down or the pHin servers became unavailable. The right solution is to make the pHin REST call and capture an exception.

**Comment by StarDylan** [comment]
Ok changed it with a new method to check the connectivity.

**Comment by StarDylan** [comment]
Ok will do

**Comment by StarDylan** [comment]
Ok fixed that too

**Review by starcode911 — APPROVED** [review]

**Pull request merged**
